env:
  - GO111MODULE=on
  - CGO_ENABLED=0
  - PROJECT_NAME=goimports-reviser
  - PROJECT_USER=odenio

before:
  hooks:
    - go mod download

builds:
  - id: goimports-reviser-amd64
    binary: goimports-reviser
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w -X "main.Tag={{ .Tag }}" -X "main.Commit={{ .FullCommit }}" -X "main.SourceURL={{ .GitURL }}" -X "main.GoVersion={{ .Env.GO_VERSION }}"

  - id: goimports-reviser-darwin-amd64
    binary: goimports-reviser
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X "main.Tag={{ .Tag }}" -X "main.Commit={{ .FullCommit }}" -X "main.SourceURL={{ .GitURL }}" -X "main.GoVersion={{ .Env.GO_VERSION }}"

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  prerelease: auto
  github:
    owner: odenio
    name: goimports-reviser
